### ISSUE TITLE
建议去掉事件隐藏(event_toggle)功能

### ISSUE THREAD

**Issue by Gwill** [GDG-Xian/crx-tower#16]
这个功能太坑了，好难用，还是去掉吧。具体的表现就是事件都隐藏了，但是 toggle 按钮经常不见，而且就算有 toggle 按钮也还得增加操作步骤才能看到事件，不值得。

**Comment by greatghoul** [comment]
感谢反馈，这个功能不会去掉，**因为它是我自己的一个需求**，但你说的问题确实存在。

目前扩展只能对已有的事件列表进行 toggle，新增的事件它就不能生效了，除非刷新页面，这是一个问题，我会在下一个版本解决。

随着我使用 tower 越来越频繁，自然会有更多定制的功能加入，这些首先是肯定是为了满足我自己的，但既然做成了公开的软件，肯定不能符合所有人的需求，所以下个版本也会**加入对于各个功能的开关**（我其实一开始就是这么设计的，每个附加的功能都使用独立的模块来实现，就是为了能够单独的启用和停用）。

在这之前，请先忍耐，对于新增的事件，只能通过刷新来生效了。

**Comment by Gwill** [comment]
主要是会影响到 “动态” 栏目中的条目展示

**Comment by greatghoul** [comment]
原来如此，我会的新版本中将这个功能在动态页面中禁用的。
