### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by Passluo** [GDG-Xian/crx-tower#23]
![image](https://user-images.githubusercontent.com/1725737/30261811-ead14636-9700-11e7-89ae-9fcb6d985172.png)

Win 10 Home 的版本 61.0.3163.79 （32 位）

装了插件以后动态页显示出错

**Comment by greatghoul** [comment]
时间长没有维护这个了，我抽时间更新一下，以适应最新的 Tower 页面结构。
你可以暂时先禁用扩展。
