### ISSUE TITLE
用不了了吗

### ISSUE THREAD

**Issue by terranc** [GDG-Xian/crx-tower#25]
ver 1.3

**Comment by greatghoul** [comment]
我想可能是之前的存储的数据格式出现了错误，你可以在 Tower 页面上打开 Chrome 开发人员工具，在 Local Storage 里面清除 `tp_` 开头的条目，或者干脆全选清除，然后再刷新页面，重新加载扩展。

**Comment by greatghoul** [comment]
![](https://ws1.sinaimg.cn/large/630b63b5ly1fl9vespjb8j21ef08wdja.jpg)

**Comment by terranc** [comment]
@greatghoul 全部清理了，也重新登录了，还是没有用。ls 没有找到 tp_开头的东西

**Comment by greatghoul** [comment]
你的 tower 域名是不是 hk 的？

**Comment by terranc** [comment]
不是呀，就是 https://tower.im

**Comment by greatghoul** [comment]
console 也没有吐什么异常吗？

![image](https://user-images.githubusercontent.com/208966/32895328-4fd063a0-caa5-11e7-8df0-c2a9658f6c82.png)

另外这个菜单项也看不到吗？

**Comment by terranc** [comment]
![image](https://user-images.githubusercontent.com/224353/32927110-780ef9b0-cb10-11e7-87c7-51b0d0edb2ee.png)

**Comment by greatghoul** [comment]
是打包的问题，你可以试试这个版本。
https://github.com/GDG-Xian/crx-tower/releases/tag/v1.3.1

或者等商店更新。
